[package]
name = "csgdb-storage"
description = "Transaction kernel adapter for CSGDB"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[features]
default = []
fault-injection = []

[dependencies]
csgdb-core = { path = "../csgdb-core" }
rusqlite = { version = "0.39.0", default-features = false, features = [
    "bundled-sqlcipher-vendored-openssl",
    "cache",
    "modern_sqlite",
] }

[lints]
workspace = true
