[package]
name = "csgdb-ffi"
description = "Stable C ABI for CSGDB"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "csgdb"
crate-type = ["cdylib", "staticlib"]
doc = false

[dependencies]
csgdb-api = { package = "csgdb", path = "../csgdb" }
csgdb-core = { path = "../csgdb-core" }
libsqlite3-sys = { version = "0.37.0", features = [
    "bundled-sqlcipher-vendored-openssl",
] }

[lints]
workspace = true
