[package]
name = "csgdb"
description = "Rust API for the CSGDB embedded agent database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
fault-injection = ["csgdb-storage/fault-injection"]

[dependencies]
csgdb-core = { path = "../csgdb-core" }
csgdb-derive = { path = "../csgdb-derive" }
csgdb-storage = { path = "../csgdb-storage" }

[lints]
workspace = true
