[package]
name = "csgdb-cli"
description = "Command-line tools for CSGDB"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "csg"
path = "src/main.rs"

[dependencies]
csgdb-core = { path = "../csgdb-core" }

[lints]
workspace = true
